
services:
  mongodb:
    image: mongo:5.0
    container_name: krishi-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: krishi-backend
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:admin123@mongodb:27017/krishi-db?authSource=admin
      - ML_SERVICE_URL=http://localhost:8000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  ml-service:
    build: ./ml-service
    container_name: krishi-ml
    environment:
      - MONGODB_URI=mongodb://admin:admin123@mongodb:27017/krishi-db?authSource=admin
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./ml-service:/app

  frontend:
    build: ./frontend
    container_name: krishi-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src

volumes:
  mongodb_data: